version: "3"

services:
  webserver:
    build: 
      context: ./docker/php
    container_name: 'backend'
    restart: 'always'
    ports:
      - "80:80"
      - "443:443"
    links: 
      - mysql
    volumes: 
      - ${DOCUMENT_ROOT-./www}:/var/www/html
      - ${PHP_INI-./docker/php/php.ini}:/usr/local/etc/php/php.ini
      - ${APACHE_VHOSTS_DIR-./docker/apache/vhosts}:/etc/apache2/sites-enabled
      - ${APACHE_CERTIFICATES_DIR-./docker/apache/ssl}:/etc/ssl/crt
      - ${APACHE_LOG_DIR-./docker/logs/apache2}:/var/log/apache2
  mysql:
    build: ./docker/mysql
    command: ['--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci','--default-authentication-plugin=mysql_native_password']
    container_name: 'bbdd'
    restart: 'always'
    ports:
      - "3306:3306"
    volumes: 
      - ${MYSQL_DATA_DIR-./docker/mysql/data}:/var/lib/mysql
      - ${MYSQL_LOG_DIR-./docker/logs/mysql}:/var/log/mysql
    environment:
      MYSQL_ROOT_PASSWORD: tiger
      MYSQL_DATABASE: png
      MYSQL_USER: png
      MYSQL_PASSWORD: png
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: 'phpmyadmin'
    links:
      - mysql
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
    ports:
      - '8080:80'
    volumes: 
      - /sessions
  redis:
    container_name: 'redis'
    image: redis:latest
    ports:
      - "6379:6379"