version: "3"

services:
  webserver:
    build: 
      context: ./docker/php
    container_name: 'backend'
    restart: 'always'
    ports:
      - "80:80"
      - "443:443"
    links: 
      - mysql
    volumes: 
      - ./www:/var/www/html
      - ./docker/php/php.ini:/usr/local/etc/php/php.ini
      - ./docker/apache/vhosts:/etc/apache2/sites-enabled
      - ./docker/apache/ssl:/etc/ssl/crt
      - ./docker/logs/apache2:/var/log/apache2
  mysql:
    build: ./docker/mysql
    command: ['--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci','--default-authentication-plugin=mysql_native_password']
    container_name: 'bbdd'
    restart: 'always'
    ports:
      - "3306:3306"
    volumes: 
      - ./docker/mysql/data:/var/lib/mysql
      - ./docker/logs/mysql:/var/log/mysql
    env_file:
      - ./docker/mysql/mysql.env
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: 'phpmyadmin'
    links:
      - mysql
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
    ports:
      - '8080:80'
    volumes:
      - /sessions
  redis:
    container_name: 'redis'
    image: redis:latest
    ports:
      - "6379:6379"